default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    gamma: 0.99
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 2500
    use_recurrent: false
    use_curiosity: false
    curiosity_strength: 0.01
    curiosity_enc_size: 128

Walk:
    normalize: true
    num_epoch: 3
    time_horizon: 1024
    batch_size: 2048
    buffer_size: 20480
    gamma: 0.995
    max_steps: 5.0e6
    num_layers: 2
    hidden_units: 256

Navigate:
    time_horizon: 1024
    batch_size: 1024
    buffer_size: 10240
    gamma: 0.995
    hidden_units: 64
    num_layers: 1
    max_steps: 1.0e6
    num_epoch: 3

Shoot:
    normalize: true
    time_horizon: 128
    batch_size: 128
    buffer_size: 2048
    hidden_units: 32
    num_layers: 1
    max_steps: 1.0e5
    num_epoch: 3